server:
  port: 7000

auth0:
  audience: https://otherworldapi.com/auth
  domain: overworld.eu.auth0.com

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Yusdawg123ss
    initialization-mode: always

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc:
          timezone: UTC

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/